//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeEnchant.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeEnchant.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load End. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadEnd {
            get {
                return ResourceManager.GetString("LoadEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load Start. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadStart {
            get {
                return ResourceManager.GetString("LoadStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rarity_Common {
            get {
                return ResourceManager.GetString("Rarity_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Epic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rarity_Epic {
            get {
                return ResourceManager.GetString("Rarity_Epic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Legendary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rarity_Legendary {
            get {
                return ResourceManager.GetString("Rarity_Legendary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OverLegendary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rarity_OverLegendary {
            get {
                return ResourceManager.GetString("Rarity_OverLegendary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rare に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rarity_Rare {
            get {
                return ResourceManager.GetString("Rarity_Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SuperRare に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rarity_SuperRare {
            get {
                return ResourceManager.GetString("Rarity_SuperRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UltraRare に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rarity_UltraRare {
            get {
                return ResourceManager.GetString("Rarity_UltraRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uncommon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rarity_Uncommon {
            get {
                return ResourceManager.GetString("Rarity_Uncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown Rarity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rarity_Unknown {
            get {
                return ResourceManager.GetString("Rarity_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected enchantments :  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectingEnchant {
            get {
                return ResourceManager.GetString("SelectingEnchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select up to four enchantments to be granted, and press Confirm. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TopLabel1 {
            get {
                return ResourceManager.GetString("TopLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected enchantments will be shown red color.  If you select again, will be deselected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TopLabel2 {
            get {
                return ResourceManager.GetString("TopLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
